// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package ds.smartwarehouse.managementService;

public interface batteryLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:managementService.batteryLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 battery = 1;</code>
   */
  int getBattery();
}
