// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package ds.smartwarehouse.managementService;

public interface equipCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:managementService.equipCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();
}
