// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package ds.smartwarehouse.managementService;

public final class ManagementServiceImpl {
  private ManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_managementService_equipCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_managementService_equipCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_managementService_workHours_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_managementService_workHours_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_managementService_batteryLevel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_managementService_batteryLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Management.proto\022\021managementService\"\031\n" +
      "\tequipCode\022\014\n\004code\030\001 \001(\005\"\032\n\tworkHours\022\r\n" +
      "\005hours\030\001 \001(\005\"\037\n\014batteryLevel\022\017\n\007battery\030" +
      "\001 \001(\0052\244\001\n\nManagement\022H\n\010getHours\022\034.manag" +
      "ementService.equipCode\032\034.managementServi" +
      "ce.workHours\"\000\022L\n\tlowCharge\022\037.management" +
      "Service.batteryLevel\032\034.managementService" +
      ".equipCode\"\000B>\n#ds.smartwarehouse.manage" +
      "mentServiceB\025ManagementServiceImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_managementService_equipCode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_managementService_equipCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_managementService_equipCode_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_managementService_workHours_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_managementService_workHours_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_managementService_workHours_descriptor,
        new java.lang.String[] { "Hours", });
    internal_static_managementService_batteryLevel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_managementService_batteryLevel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_managementService_batteryLevel_descriptor,
        new java.lang.String[] { "Battery", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
