// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package ds.smartwarehouse.managementService;

public interface workHoursOrBuilder extends
    // @@protoc_insertion_point(interface_extends:managementService.workHours)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hours = 1;</code>
   */
  int getHours();
}
