// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingService.proto

package ds.smartwarehouse.pickingservice;

public interface confirmOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingService.confirmOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool order = 1;</code>
   */
  boolean getOrder();
}
