// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingService.proto

package ds.smartwarehouse.pickingservice;

public interface itemStoredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingService.itemStored)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool stored = 1;</code>
   */
  boolean getStored();
}
