// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingService.proto

package ds.smartwarehouse.pickingservice;

public interface itemNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingService.itemName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
