// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingService.proto

package ds.smartwarehouse.pickingservice;

public interface orderListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pickingService.orderList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string list = 1;</code>
   */
  java.lang.String getList();
  /**
   * <code>string list = 1;</code>
   */
  com.google.protobuf.ByteString
      getListBytes();
}
