// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PickingService.proto

package ds.smartwarehouse.pickingservice;

public final class PickingServiceImpl {
  private PickingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingService_orderList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingService_orderList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingService_itemName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingService_itemName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingService_confirmOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingService_confirmOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pickingService_itemStored_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pickingService_itemStored_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PickingService.proto\022\016pickingService\"\031" +
      "\n\torderList\022\014\n\004list\030\001 \001(\t\"\030\n\010itemName\022\014\n" +
      "\004name\030\001 \001(\t\"\035\n\014confirmOrder\022\r\n\005order\030\001 \001" +
      "(\010\"\034\n\nitemStored\022\016\n\006stored\030\001 \001(\0102\235\001\n\007Pic" +
      "king\022G\n\010getOrder\022\031.pickingService.orderL" +
      "ist\032\034.pickingService.confirmOrder\"\000(\001\022I\n" +
      "\013sortProduct\022\030.pickingService.itemName\032\032" +
      ".pickingService.itemStored\"\000(\0010\001B8\n ds.s" +
      "martwarehouse.pickingserviceB\022PickingSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pickingService_orderList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pickingService_orderList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingService_orderList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_pickingService_itemName_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pickingService_itemName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingService_itemName_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_pickingService_confirmOrder_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pickingService_confirmOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingService_confirmOrder_descriptor,
        new java.lang.String[] { "Order", });
    internal_static_pickingService_itemStored_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pickingService_itemStored_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pickingService_itemStored_descriptor,
        new java.lang.String[] { "Stored", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
