// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryService.proto

package ds.inventoryservice;

public interface confirmOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventoryService.confirmOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool order = 1;</code>
   */
  boolean getOrder();
}
