// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryService.proto

package ds.inventoryservice;

public interface itemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventoryService.item)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
