// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryService.proto

package ds.smartwarehouse.inventoryservice;

public final class InventoryServiceImpl {
  private InventoryServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventoryService_itemCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventoryService_itemCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventoryService_item_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventoryService_item_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventoryService_confirmOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventoryService_confirmOrder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026InventoryService.proto\022\020inventoryServi" +
      "ce\"\030\n\010itemCode\022\014\n\004code\030\001 \001(\005\"\024\n\004item\022\014\n\004" +
      "name\030\001 \001(\t\"\035\n\014confirmOrder\022\r\n\005order\030\001 \001(" +
      "\0102\243\001\n\020inventoryService\022B\n\nsearchItem\022\032.i" +
      "nventoryService.itemCode\032\026.inventoryServ" +
      "ice.item\"\000\022K\n\tmakeOrder\022\032.inventoryServi" +
      "ce.itemCode\032\036.inventoryService.confirmOr" +
      "der\"\0000\001B<\n\"ds.smartwarehouse.inventoryse" +
      "rviceB\024InventoryServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_inventoryService_itemCode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventoryService_itemCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventoryService_itemCode_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_inventoryService_item_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventoryService_item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventoryService_item_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_inventoryService_confirmOrder_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_inventoryService_confirmOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventoryService_confirmOrder_descriptor,
        new java.lang.String[] { "Order", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
