// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryService.proto

package ds.smartwarehouse.inventoryservice;

public interface itemCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventoryService.itemCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();
}
